version: "3"
services: 
  csvserver: 
    image: "infracloudio/csvserver:latest"
    container_name: csvserver
    environment: 
      - CSVSERVER_BORDER=Orange
    ports: 
      - "9393:9300"
    volumes: 
      - /root/testscript/inputFile:/csvserver/inputdata
